<#
  build-data.ps1
  Pulls each dataset straight to disk, then writes clean.csv and data.js.
  This is the SOP-02 step, automated: the raw download stays untouched, and
  every value the site renders traces back to it.

  Usage:  powershell -File tools/build-data.ps1
#>

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$stamp = Get-Date -Format 'yyyy-MM'

# Entities that stand for groups rather than countries. Kept in one list so
# that both datasets rank the same way.
$aggregates = @(
  'World', 'European Union (27)', 'Europe', 'Asia', 'Africa',
  'North America', 'South America', 'Oceania', 'Rest of the world',
  'High-income countries', 'Low-income countries',
  'Lower-middle-income countries', 'Upper-middle-income countries'
)

$datasets = @(
  @{
    id        = 'ev-sales-share-by-country'
    grapher   = 'electric-car-sales-share'
    column    = 'ev_sales_share'
    valueCol  = 'ev_sales_share_percent'
    scale     = 1
    decimals  = 1
    topN      = 15
    seriesFor = 'World'
    seriesFrom= 2010
  },
  @{
    id        = 'electric-car-sales-by-country'
    grapher   = 'electric-car-sales'
    column    = 'ev_sales'
    valueCol  = 'ev_sales_thousands'
    scale     = 0.001
    decimals  = 0
    topN      = 15
    seriesFor = 'World'
    seriesFrom= 2010
  }
)

function Write-Utf8($path, $body) {
  $dir = Split-Path -Parent $path
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  Set-Content -Path $path -Value $body -Encoding utf8 -NoNewline
}

foreach ($d in $datasets) {
  Write-Host "=== $($d.id) ==="
  $dir = Join-Path $root "data\$($d.id)"
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

  $rawPath = Join-Path $dir "raw_$stamp.csv"
  $url = "https://ourworldindata.org/grapher/$($d.grapher).csv?csvType=full&useColumnShortNames=true"
  Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 60 -OutFile $rawPath
  Write-Host "  raw saved: $rawPath"

  $rows = Import-Csv $rawPath
  $col = $d.column
  $latest = ($rows | Measure-Object -Property year -Maximum).Maximum
  Write-Host "  latest year: $latest"

  $ranked = $rows |
    Where-Object { $_.year -eq $latest -and $_.code -ne '' -and $aggregates -notcontains $_.entity -and $_.$col -ne '' } |
    Sort-Object { [double]$_.$col } -Descending |
    Select-Object -First $d.topN

  $series = $rows |
    Where-Object { $_.entity -eq $d.seriesFor -and [int]$_.year -ge $d.seriesFrom -and $_.$col -ne '' } |
    Sort-Object { [int]$_.year }

  # ---- clean.csv, the record of truth --------------------------------------
  # SOP-02: no rounding in storage. Source values land here verbatim, and the
  # scaling that makes a chart readable happens only in data.js below.
  $lines = @("country,$col,year")
  foreach ($r in $ranked) {
    $lines += "$($r.entity),$($r.$col),$latest"
  }
  Write-Utf8 (Join-Path $dir 'clean.csv') (($lines -join "`n") + "`n")

  # ---- data.js, the render-ready copy --------------------------------------
  $rowsJs = ($ranked | ForEach-Object {
    $v = [math]::Round([double]$_.$col * $d.scale, $d.decimals)
    "    { label: '$($_.entity -replace "'", "\'")', value: $v }"
  }) -join ",`n"

  $seriesJs = ($series | ForEach-Object {
    $v = [math]::Round([double]$_.$col * $d.scale, $d.decimals)
    "    { label: '$($_.year)', value: $v }"
  }) -join ",`n"

  $js = @"
/* ==========================================================================
   Dataset: $($d.id)
   Generated by tools/build-data.ps1 on $(Get-Date -Format 'yyyy-MM-dd').
   Do not edit by hand. Edit the generator, then run it again.
   Traces back to data/$($d.id)/raw_$stamp.csv
   ========================================================================== */

window.DATASETS = window.DATASETS || {};

window.DATASETS['$($d.id)'] = {
  id: '$($d.id)',
  placeholder: false,
  latestYear: $latest,
  rows: [
$rowsJs
  ],
  series: [
$seriesJs
  ]
};
"@
  Write-Utf8 (Join-Path $dir 'data.js') $js

  Write-Host "  wrote clean.csv and data.js ($($ranked.Count) rows, $($series.Count) series points)"
}

Write-Host ''
Write-Host 'Done. Check meta.json by hand: licence and credit wording stay a human decision.'
